env:
  global:
    - ARTIFACTORY_USER=travis-rw-spt-infrastructure
    #ARTIFACTORY_PASSWORD
    - secure: "f3yLsuyrATKjA0Smn1OkhYpX83wTKj+nUbkd5Z0giyeiazfj4aLFJDIpsIDomfZ3Y39C0/5bG+uIsmYvF0JE++qQp5xsxAMgJa+0WxQYm9ssllXAqJOqJcT7yqQgH6uiUq+IoM92xUqqmTIXRl0C9Nh5MckcTuL2UMr/a9v2JAkA0B5/AKhaYhho/A/rnNn8QDlAwGoZzFzWt7HcyM74MM3q4X6Ojtk/WGB2TnZVc9+PO5RSuOxXLnSuIc1JRkEuZ3Ttg3TNuRW19MaX2FQadj+kaRvfzJJAukLpkOFzE+BESI+hW0g17BmeRgpkklzNrBbZeFodetlbZEelt/UZ/zaYizrN4hpaLllTrENje3Dm9ZuNlfQ8K6EJAL9Y7fmP7l+spdKdKCwqqeDTvwM436ybDmoS1VB63Jcj0X9RfssKPi2zrNcmMZlDKeC1nFosXeW9ClvgC5kgkc5GSyWGW+KHDcnj3LnOgoq+cjg+hab/F0p8iPW/V8kYK4pGGZ1RzEzFoEC6BHFISO3hYxsMaCGm4ZOMWT7cYFvBcUNIJoQzevMl5wQmhTS+RlNRCvaYQYxFPYfyTT0yQwckDnm7iG810lu6bstG+cgf4Z9GVd4P+Hy8aoVvpL5Izo5ydiLSQFVSwy2kZBViCLVSiKwOpcXvIETZbOoq7auN46y1dec="
    - ARTIFACTORY_UPLOAD_PATH=yum-local/infrastructure/platform/cre/tardis/mesos2iam/

language: go

go: 1.7.3

go_import_path: github.schibsted.io/spt-infrastructure/mesos2iam.git

install:
  - go get github.com/JFrogDev/artifactory-cli-go/...
  - go get github.com/golang/lint/golint
  - go get github.com/jessevdk/go-flags
  - go get github.com/tobi/airbrake-go
  - go get github.com/getsentry/raven-go
  - gem install fpm
  - sudo apt-get install rpm

before_script:
  - art config --url=https://artifacts.schibsted.io/artifactory --user=${ARTIFACTORY_USER} --password=${ARTIFACTORY_PASSWORD}

script:
  - make lint
  - make vet
  - make test
  - make build
  - bash -ex script/build-rpm.sh
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then art upload *.rpm ${ARTIFACTORY_UPLOAD_PATH}; fi
